modLoader = "javafml"
loaderVersion = "[40,)"
license = "AGPL v3"
[[mods]]
modId = "firesafety"
version = "${file.jarVersion}"
displayName = "FireSafety"
credits = "Part of sounds and concepts from the game WOWS"
authors = "Nova Committee"
description = "Unregulated fire usage, loved ones end up in tears."